apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}          # ★ 必须带 app 标签，ServiceMonitor 靠它匹配
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: http                 # ★ 端口命名，ServiceMonitor 靠它定位
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
